{% set name = "myst-sphinx-gallery" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/myst_sphinx_gallery-{{ version }}.tar.gz
  sha256: ba9b892abfe1f6ed8f9b9410a83ff412f995f075d2c3fd63bbf0c0a3190e1ad1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - pillow
    - myst-nb
    - sphinx-design

test:
  imports:
    - myst_sphinx_gallery
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Fanchengyan/myst-sphinx-gallery
  summary: A Sphinx extension that builds galleries of examples from any set of myst-style markdown/notebook or rst files.
  dev_url: https://github.com/Fanchengyan/myst-sphinx-gallery
  doc_url: https://myst-sphinx-gallery.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Fanchengyan
